name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
        run:
            shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
            install: mingw-w64-x86_64-toolchain
            msystem: mingw64
            release: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw73'
          dir: '${{github.workspace}}/qt/'
          install-deps: 'true'

      - name: List files in Qt
        run: find ${{env.Qt5_Dir}}

      - uses: actions/checkout@v2

      - name: Build FluentUI
        run: |
            cd ..
            git clone https://github.com/zhuzichu520/FluentUI.git ./
            cd ./FluentUI
            cmake -DCMAKE_PREFIX_PATH=${{env.Qt5_Dir}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" -B '${{github.workspace}}'/build
            cmake --build '${{github.workspace}}'/build --target all
            cd ..

      - name: Build memory
        run: |
            cd ./memory
            cmake -DCMAKE_PREFIX_PATH=${{env.Qt5_Dir}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" -B '${{github.workspace}}'/build
            cmake --build '${{github.workspace}}'/build --target all
            cmake --build '${{github.workspace}}'/build --target Script-DeployRelease
            powershell Compress-Archive -Path ./dist -DestinationPath memory.zip
